version: '3.8'
services:
  ping:
    container_name: ping
    build: 
      context: ../ping
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      pong:
        condition: service_started
    environment:
      - SERVER_ADDRESS=:8080
      - PONG_SERVER_ADDRESS=http://pong:7070/api/v1/pong
      - SERVICE_NAME=ping
      - TRACING_ENDPOINT=jaeger:4318
    ports:
      - "8080:8080"
  pong:
    container_name: pong
    build:
      context: ../pong
      dockerfile: Dockerfile
    restart: on-failure
    environment:
      - SERVER_ADDRESS=:7070
      - SERVICE_NAME=pong 
      - TRACING_ENDPOINT=jaeger:4318
  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
    ports:
      - "16686:16686"
      - "4318:4318"
      - "4317:4317"