global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'ping'
    static_configs:
      - targets: ['ping:8080']
  - job_name: 'pong'
    static_configs:
      - targets: ['pong:7070']
